---
- name: Install and configure Chrony
  hosts: all
  become: yes
  tasks:
    - name: Install Chrony package
      yum:
        name: chrony
        state: present

    - name: Configure NTP server in Chrony
      lineinfile:
        path: /etc/chrony.conf
        regexp: '^server'
        line: "server chronyupdated.amigo.local iburst"
        state: present

    - name: Start and enable Chrony service
      service:
        name: chronyd
        state: started
        enabled: yes

    - name: Restart Chrony service to apply changes
      service:
        name: chronyd
        state: restarted
